package io.bifri.interview.cmp.padel.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Light
internal val PrimaryLight = Color(0xFF006A60)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFF9DF2E4)
internal val OnPrimaryContainerLight = Color(0xFF005048)
internal val SecondaryLight = Color(0xFF315F9F)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFD6E3FF)
internal val OnSecondaryContainerLight = Color(0xFF17477F)
internal val TertiaryLight = Color(0xFF8B5000)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFFFDDB8)
internal val OnTertiaryContainerLight = Color(0xFF6A3B00)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF93000A)
internal val BackgroundLight = Color(0xFFF6FBF8)
internal val OnBackgroundLight = Color(0xFF171D1B)
internal val SurfaceLight = Color(0xFFF6FBF8)
internal val OnSurfaceLight = Color(0xFF171D1B)
internal val SurfaceVariantLight = Color(0xFFDAE5E1)
internal val OnSurfaceVariantLight = Color(0xFF3F4946)
internal val OutlineLight = Color(0xFF6F7976)
internal val OutlineVariantLight = Color(0xFFBEC9C5)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF2C3230)
internal val InverseOnSurfaceLight = Color(0xFFEDF2EF)
internal val InversePrimaryLight = Color(0xFF81D5C8)
internal val SurfaceDimLight = Color(0xFFD6DBD8)
internal val SurfaceBrightLight = Color(0xFFF6FBF8)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF0F5F2)
internal val SurfaceContainerLight = Color(0xFFEAEFEC)
internal val SurfaceContainerHighLight = Color(0xFFE4E9E6)
internal val SurfaceContainerHighestLight = Color(0xFFDEE4E1)

// Light Medium Contrast
internal val PrimaryLightMediumContrast = Color(0xFF003D36)
internal val OnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val PrimaryContainerLightMediumContrast = Color(0xFF19796E)
internal val OnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val SecondaryLightMediumContrast = Color(0xFF003B70)
internal val OnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val SecondaryContainerLightMediumContrast = Color(0xFF416EAE)
internal val OnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val TertiaryLightMediumContrast = Color(0xFF563000)
internal val OnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val TertiaryContainerLightMediumContrast = Color(0xFF9D5E12)
internal val OnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val ErrorLightMediumContrast = Color(0xFF740006)
internal val OnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val ErrorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val OnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val BackgroundLightMediumContrast = Color(0xFFF6FBF8)
internal val OnBackgroundLightMediumContrast = Color(0xFF171D1B)
internal val SurfaceLightMediumContrast = Color(0xFFF6FBF8)
internal val OnSurfaceLightMediumContrast = Color(0xFF0D1211)
internal val SurfaceVariantLightMediumContrast = Color(0xFFDAE5E1)
internal val OnSurfaceVariantLightMediumContrast = Color(0xFF2F3936)
internal val OutlineLightMediumContrast = Color(0xFF4B5552)
internal val OutlineVariantLightMediumContrast = Color(0xFF66716D)
internal val ScrimLightMediumContrast = Color(0xFF000000)
internal val InverseSurfaceLightMediumContrast = Color(0xFF2C3230)
internal val InverseOnSurfaceLightMediumContrast = Color(0xFFEDF2EF)
internal val InversePrimaryLightMediumContrast = Color(0xFF81D5C8)
internal val SurfaceDimLightMediumContrast = Color(0xFFC2C8C5)
internal val SurfaceBrightLightMediumContrast = Color(0xFFF6FBF8)
internal val SurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLightMediumContrast = Color(0xFFF0F5F2)
internal val SurfaceContainerLightMediumContrast = Color(0xFFE4E9E6)
internal val SurfaceContainerHighLightMediumContrast = Color(0xFFD9DEDB)
internal val SurfaceContainerHighestLightMediumContrast = Color(0xFFCED3D0)

// Light High Contrast
internal val PrimaryLightHighContrast = Color(0xFF00322C)
internal val OnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val PrimaryContainerLightHighContrast = Color(0xFF00534B)
internal val OnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val SecondaryLightHighContrast = Color(0xFF002F5C)
internal val OnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val SecondaryContainerLightHighContrast = Color(0xFF194A82)
internal val OnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val TertiaryLightHighContrast = Color(0xFF462600)
internal val OnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val TertiaryContainerLightHighContrast = Color(0xFF6D3D00)
internal val OnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val ErrorLightHighContrast = Color(0xFF600004)
internal val OnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val ErrorContainerLightHighContrast = Color(0xFF98000A)
internal val OnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val BackgroundLightHighContrast = Color(0xFFF6FBF8)
internal val OnBackgroundLightHighContrast = Color(0xFF171D1B)
internal val SurfaceLightHighContrast = Color(0xFFF6FBF8)
internal val OnSurfaceLightHighContrast = Color(0xFF000000)
internal val SurfaceVariantLightHighContrast = Color(0xFFDAE5E1)
internal val OnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val OutlineLightHighContrast = Color(0xFF252F2C)
internal val OutlineVariantLightHighContrast = Color(0xFF414B48)
internal val ScrimLightHighContrast = Color(0xFF000000)
internal val InverseSurfaceLightHighContrast = Color(0xFF2C3230)
internal val InverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val InversePrimaryLightHighContrast = Color(0xFFA8F9EC)
internal val SurfaceDimLightHighContrast = Color(0xFFB4BAB7)
internal val SurfaceBrightLightHighContrast = Color(0xFFF6FBF8)
internal val SurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLightHighContrast = Color(0xFFEDF2EF)
internal val SurfaceContainerLightHighContrast = Color(0xFFDEE4E1)
internal val SurfaceContainerHighLightHighContrast = Color(0xFFD0D6D3)
internal val SurfaceContainerHighestLightHighContrast = Color(0xFFC2C8C5)

// Dark
internal val PrimaryDark = Color(0xFF81D5C8)
internal val OnPrimaryDark = Color(0xFF003731)
internal val PrimaryContainerDark = Color(0xFF005048)
internal val OnPrimaryContainerDark = Color(0xFF9DF2E4)
internal val SecondaryDark = Color(0xFFA9C7FF)
internal val OnSecondaryDark = Color(0xFF00315F)
internal val SecondaryContainerDark = Color(0xFF17477F)
internal val OnSecondaryContainerDark = Color(0xFFD6E3FF)
internal val TertiaryDark = Color(0xFFFFB95E)
internal val OnTertiaryDark = Color(0xFF4A2800)
internal val TertiaryContainerDark = Color(0xFF6A3B00)
internal val OnTertiaryContainerDark = Color(0xFFFFDDB8)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF0F1513)
internal val OnBackgroundDark = Color(0xFFDEE4E1)
internal val SurfaceDark = Color(0xFF0F1513)
internal val OnSurfaceDark = Color(0xFFDEE4E1)
internal val SurfaceVariantDark = Color(0xFF3F4946)
internal val OnSurfaceVariantDark = Color(0xFFBEC9C5)
internal val OutlineDark = Color(0xFF88938F)
internal val OutlineVariantDark = Color(0xFF3F4946)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFDEE4E1)
internal val InverseOnSurfaceDark = Color(0xFF2C3230)
internal val InversePrimaryDark = Color(0xFF006A60)
internal val SurfaceDimDark = Color(0xFF0F1513)
internal val SurfaceBrightDark = Color(0xFF353B39)
internal val SurfaceContainerLowestDark = Color(0xFF0A0F0E)
internal val SurfaceContainerLowDark = Color(0xFF171D1B)
internal val SurfaceContainerDark = Color(0xFF1B211F)
internal val SurfaceContainerHighDark = Color(0xFF252B29)
internal val SurfaceContainerHighestDark = Color(0xFF303634)

// Dark Medium Contrast
internal val PrimaryDarkMediumContrast = Color(0xFFA5F6E9)
internal val OnPrimaryDarkMediumContrast = Color(0xFF002C27)
internal val PrimaryContainerDarkMediumContrast = Color(0xFF4F9E92)
internal val OnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val SecondaryDarkMediumContrast = Color(0xFFD1E1FF)
internal val OnSecondaryDarkMediumContrast = Color(0xFF00264B)
internal val SecondaryContainerDarkMediumContrast = Color(0xFF7398DB)
internal val OnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val TertiaryDarkMediumContrast = Color(0xFFFFD9AD)
internal val OnTertiaryDarkMediumContrast = Color(0xFF3A1E00)
internal val TertiaryContainerDarkMediumContrast = Color(0xFFCA8434)
internal val OnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val ErrorDarkMediumContrast = Color(0xFFFFD2CC)
internal val OnErrorDarkMediumContrast = Color(0xFF540003)
internal val ErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val OnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val BackgroundDarkMediumContrast = Color(0xFF0F1513)
internal val OnBackgroundDarkMediumContrast = Color(0xFFDEE4E1)
internal val SurfaceDarkMediumContrast = Color(0xFF0F1513)
internal val OnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val SurfaceVariantDarkMediumContrast = Color(0xFF3F4946)
internal val OnSurfaceVariantDarkMediumContrast = Color(0xFFD4DFDB)
internal val OutlineDarkMediumContrast = Color(0xFFAAB5B1)
internal val OutlineVariantDarkMediumContrast = Color(0xFF88938F)
internal val ScrimDarkMediumContrast = Color(0xFF000000)
internal val InverseSurfaceDarkMediumContrast = Color(0xFFDEE4E1)
internal val InverseOnSurfaceDarkMediumContrast = Color(0xFF252B29)
internal val InversePrimaryDarkMediumContrast = Color(0xFF00524A)
internal val SurfaceDimDarkMediumContrast = Color(0xFF0F1513)
internal val SurfaceBrightDarkMediumContrast = Color(0xFF414745)
internal val SurfaceContainerLowestDarkMediumContrast = Color(0xFF050908)
internal val SurfaceContainerLowDarkMediumContrast = Color(0xFF191F1D)
internal val SurfaceContainerDarkMediumContrast = Color(0xFF232927)
internal val SurfaceContainerHighDarkMediumContrast = Color(0xFF2E3432)
internal val SurfaceContainerHighestDarkMediumContrast = Color(0xFF393F3D)

// Dark High Contrast
internal val PrimaryDarkHighContrast = Color(0xFFB8FFF3)
internal val OnPrimaryDarkHighContrast = Color(0xFF000000)
internal val PrimaryContainerDarkHighContrast = Color(0xFF7DD1C4)
internal val OnPrimaryContainerDarkHighContrast = Color(0xFF000E0C)
internal val SecondaryDarkHighContrast = Color(0xFFEAF1FF)
internal val OnSecondaryDarkHighContrast = Color(0xFF000000)
internal val SecondaryContainerDarkHighContrast = Color(0xFFA5C3FB)
internal val OnSecondaryContainerDarkHighContrast = Color(0xFF000D22)
internal val TertiaryDarkHighContrast = Color(0xFFFFECDC)
internal val OnTertiaryDarkHighContrast = Color(0xFF000000)
internal val TertiaryContainerDarkHighContrast = Color(0xFFFFB65A)
internal val OnTertiaryContainerDarkHighContrast = Color(0xFF170B00)
internal val ErrorDarkHighContrast = Color(0xFFFFECE9)
internal val OnErrorDarkHighContrast = Color(0xFF000000)
internal val ErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val OnErrorContainerDarkHighContrast = Color(0xFF220001)
internal val BackgroundDarkHighContrast = Color(0xFF0F1513)
internal val OnBackgroundDarkHighContrast = Color(0xFFDEE4E1)
internal val SurfaceDarkHighContrast = Color(0xFF0F1513)
internal val OnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val SurfaceVariantDarkHighContrast = Color(0xFF3F4946)
internal val OnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val OutlineDarkHighContrast = Color(0xFFE8F2EE)
internal val OutlineVariantDarkHighContrast = Color(0xFFBAC5C1)
internal val ScrimDarkHighContrast = Color(0xFF000000)
internal val InverseSurfaceDarkHighContrast = Color(0xFFDEE4E1)
internal val InverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val InversePrimaryDarkHighContrast = Color(0xFF004A43)
internal val SurfaceDimDarkHighContrast = Color(0xFF0F1513)
internal val SurfaceBrightDarkHighContrast = Color(0xFF4D5351)
internal val SurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val SurfaceContainerLowDarkHighContrast = Color(0xFF1B211F)
internal val SurfaceContainerDarkHighContrast = Color(0xFF2C3230)
internal val SurfaceContainerHighDarkHighContrast = Color(0xFF373D3B)
internal val SurfaceContainerHighestDarkHighContrast = Color(0xFF434947)

internal val LightColorScheme = lightColorScheme(
    primary = PrimaryLight,
    onPrimary = OnPrimaryLight,
    primaryContainer = PrimaryContainerLight,
    onPrimaryContainer = OnPrimaryContainerLight,
    secondary = SecondaryLight,
    onSecondary = OnSecondaryLight,
    secondaryContainer = SecondaryContainerLight,
    onSecondaryContainer = OnSecondaryContainerLight,
    tertiary = TertiaryLight,
    onTertiary = OnTertiaryLight,
    tertiaryContainer = TertiaryContainerLight,
    onTertiaryContainer = OnTertiaryContainerLight,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight,
    scrim = ScrimLight,
    inverseSurface = InverseSurfaceLight,
    inverseOnSurface = InverseOnSurfaceLight,
    inversePrimary = InversePrimaryLight,
    surfaceDim = SurfaceDimLight,
    surfaceBright = SurfaceBrightLight,
    surfaceContainerLowest = SurfaceContainerLowestLight,
    surfaceContainerLow = SurfaceContainerLowLight,
    surfaceContainer = SurfaceContainerLight,
    surfaceContainerHigh = SurfaceContainerHighLight,
    surfaceContainerHighest = SurfaceContainerHighestLight,
)

internal val DarkColorScheme = darkColorScheme(
    primary = PrimaryDark,
    onPrimary = OnPrimaryDark,
    primaryContainer = PrimaryContainerDark,
    onPrimaryContainer = OnPrimaryContainerDark,
    secondary = SecondaryDark,
    onSecondary = OnSecondaryDark,
    secondaryContainer = SecondaryContainerDark,
    onSecondaryContainer = OnSecondaryContainerDark,
    tertiary = TertiaryDark,
    onTertiary = OnTertiaryDark,
    tertiaryContainer = TertiaryContainerDark,
    onTertiaryContainer = OnTertiaryContainerDark,
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = BackgroundDark,
    onBackground = OnBackgroundDark,
    surface = SurfaceDark,
    onSurface = OnSurfaceDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    outline = OutlineDark,
    outlineVariant = OutlineVariantDark,
    scrim = ScrimDark,
    inverseSurface = InverseSurfaceDark,
    inverseOnSurface = InverseOnSurfaceDark,
    inversePrimary = InversePrimaryDark,
    surfaceDim = SurfaceDimDark,
    surfaceBright = SurfaceBrightDark,
    surfaceContainerLowest = SurfaceContainerLowestDark,
    surfaceContainerLow = SurfaceContainerLowDark,
    surfaceContainer = SurfaceContainerDark,
    surfaceContainerHigh = SurfaceContainerHighDark,
    surfaceContainerHighest = SurfaceContainerHighestDark,
)

@Suppress("UnusedPrivateProperty")
private val MediumContrastLightColorScheme = lightColorScheme(
    primary = PrimaryLightMediumContrast,
    onPrimary = OnPrimaryLightMediumContrast,
    primaryContainer = PrimaryContainerLightMediumContrast,
    onPrimaryContainer = OnPrimaryContainerLightMediumContrast,
    secondary = SecondaryLightMediumContrast,
    onSecondary = OnSecondaryLightMediumContrast,
    secondaryContainer = SecondaryContainerLightMediumContrast,
    onSecondaryContainer = OnSecondaryContainerLightMediumContrast,
    tertiary = TertiaryLightMediumContrast,
    onTertiary = OnTertiaryLightMediumContrast,
    tertiaryContainer = TertiaryContainerLightMediumContrast,
    onTertiaryContainer = OnTertiaryContainerLightMediumContrast,
    error = ErrorLightMediumContrast,
    onError = OnErrorLightMediumContrast,
    errorContainer = ErrorContainerLightMediumContrast,
    onErrorContainer = OnErrorContainerLightMediumContrast,
    background = BackgroundLightMediumContrast,
    onBackground = OnBackgroundLightMediumContrast,
    surface = SurfaceLightMediumContrast,
    onSurface = OnSurfaceLightMediumContrast,
    surfaceVariant = SurfaceVariantLightMediumContrast,
    onSurfaceVariant = OnSurfaceVariantLightMediumContrast,
    outline = OutlineLightMediumContrast,
    outlineVariant = OutlineVariantLightMediumContrast,
    scrim = ScrimLightMediumContrast,
    inverseSurface = InverseSurfaceLightMediumContrast,
    inverseOnSurface = InverseOnSurfaceLightMediumContrast,
    inversePrimary = InversePrimaryLightMediumContrast,
    surfaceDim = SurfaceDimLightMediumContrast,
    surfaceBright = SurfaceBrightLightMediumContrast,
    surfaceContainerLowest = SurfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = SurfaceContainerLowLightMediumContrast,
    surfaceContainer = SurfaceContainerLightMediumContrast,
    surfaceContainerHigh = SurfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = SurfaceContainerHighestLightMediumContrast,
)

@Suppress("UnusedPrivateProperty")
private val HighContrastLightColorScheme = lightColorScheme(
    primary = PrimaryLightHighContrast,
    onPrimary = OnPrimaryLightHighContrast,
    primaryContainer = PrimaryContainerLightHighContrast,
    onPrimaryContainer = OnPrimaryContainerLightHighContrast,
    secondary = SecondaryLightHighContrast,
    onSecondary = OnSecondaryLightHighContrast,
    secondaryContainer = SecondaryContainerLightHighContrast,
    onSecondaryContainer = OnSecondaryContainerLightHighContrast,
    tertiary = TertiaryLightHighContrast,
    onTertiary = OnTertiaryLightHighContrast,
    tertiaryContainer = TertiaryContainerLightHighContrast,
    onTertiaryContainer = OnTertiaryContainerLightHighContrast,
    error = ErrorLightHighContrast,
    onError = OnErrorLightHighContrast,
    errorContainer = ErrorContainerLightHighContrast,
    onErrorContainer = OnErrorContainerLightHighContrast,
    background = BackgroundLightHighContrast,
    onBackground = OnBackgroundLightHighContrast,
    surface = SurfaceLightHighContrast,
    onSurface = OnSurfaceLightHighContrast,
    surfaceVariant = SurfaceVariantLightHighContrast,
    onSurfaceVariant = OnSurfaceVariantLightHighContrast,
    outline = OutlineLightHighContrast,
    outlineVariant = OutlineVariantLightHighContrast,
    scrim = ScrimLightHighContrast,
    inverseSurface = InverseSurfaceLightHighContrast,
    inverseOnSurface = InverseOnSurfaceLightHighContrast,
    inversePrimary = InversePrimaryLightHighContrast,
    surfaceDim = SurfaceDimLightHighContrast,
    surfaceBright = SurfaceBrightLightHighContrast,
    surfaceContainerLowest = SurfaceContainerLowestLightHighContrast,
    surfaceContainerLow = SurfaceContainerLowLightHighContrast,
    surfaceContainer = SurfaceContainerLightHighContrast,
    surfaceContainerHigh = SurfaceContainerHighLightHighContrast,
    surfaceContainerHighest = SurfaceContainerHighestLightHighContrast,
)

@Suppress("UnusedPrivateProperty")
private val MediumContrastDarkColorScheme = darkColorScheme(
    primary = PrimaryDarkMediumContrast,
    onPrimary = OnPrimaryDarkMediumContrast,
    primaryContainer = PrimaryContainerDarkMediumContrast,
    onPrimaryContainer = OnPrimaryContainerDarkMediumContrast,
    secondary = SecondaryDarkMediumContrast,
    onSecondary = OnSecondaryDarkMediumContrast,
    secondaryContainer = SecondaryContainerDarkMediumContrast,
    onSecondaryContainer = OnSecondaryContainerDarkMediumContrast,
    tertiary = TertiaryDarkMediumContrast,
    onTertiary = OnTertiaryDarkMediumContrast,
    tertiaryContainer = TertiaryContainerDarkMediumContrast,
    onTertiaryContainer = OnTertiaryContainerDarkMediumContrast,
    error = ErrorDarkMediumContrast,
    onError = OnErrorDarkMediumContrast,
    errorContainer = ErrorContainerDarkMediumContrast,
    onErrorContainer = OnErrorContainerDarkMediumContrast,
    background = BackgroundDarkMediumContrast,
    onBackground = OnBackgroundDarkMediumContrast,
    surface = SurfaceDarkMediumContrast,
    onSurface = OnSurfaceDarkMediumContrast,
    surfaceVariant = SurfaceVariantDarkMediumContrast,
    onSurfaceVariant = OnSurfaceVariantDarkMediumContrast,
    outline = OutlineDarkMediumContrast,
    outlineVariant = OutlineVariantDarkMediumContrast,
    scrim = ScrimDarkMediumContrast,
    inverseSurface = InverseSurfaceDarkMediumContrast,
    inverseOnSurface = InverseOnSurfaceDarkMediumContrast,
    inversePrimary = InversePrimaryDarkMediumContrast,
    surfaceDim = SurfaceDimDarkMediumContrast,
    surfaceBright = SurfaceBrightDarkMediumContrast,
    surfaceContainerLowest = SurfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = SurfaceContainerLowDarkMediumContrast,
    surfaceContainer = SurfaceContainerDarkMediumContrast,
    surfaceContainerHigh = SurfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = SurfaceContainerHighestDarkMediumContrast,
)

@Suppress("UnusedPrivateProperty")
private val HighContrastDarkColorScheme = darkColorScheme(
    primary = PrimaryDarkHighContrast,
    onPrimary = OnPrimaryDarkHighContrast,
    primaryContainer = PrimaryContainerDarkHighContrast,
    onPrimaryContainer = OnPrimaryContainerDarkHighContrast,
    secondary = SecondaryDarkHighContrast,
    onSecondary = OnSecondaryDarkHighContrast,
    secondaryContainer = SecondaryContainerDarkHighContrast,
    onSecondaryContainer = OnSecondaryContainerDarkHighContrast,
    tertiary = TertiaryDarkHighContrast,
    onTertiary = OnTertiaryDarkHighContrast,
    tertiaryContainer = TertiaryContainerDarkHighContrast,
    onTertiaryContainer = OnTertiaryContainerDarkHighContrast,
    error = ErrorDarkHighContrast,
    onError = OnErrorDarkHighContrast,
    errorContainer = ErrorContainerDarkHighContrast,
    onErrorContainer = OnErrorContainerDarkHighContrast,
    background = BackgroundDarkHighContrast,
    onBackground = OnBackgroundDarkHighContrast,
    surface = SurfaceDarkHighContrast,
    onSurface = OnSurfaceDarkHighContrast,
    surfaceVariant = SurfaceVariantDarkHighContrast,
    onSurfaceVariant = OnSurfaceVariantDarkHighContrast,
    outline = OutlineDarkHighContrast,
    outlineVariant = OutlineVariantDarkHighContrast,
    scrim = ScrimDarkHighContrast,
    inverseSurface = InverseSurfaceDarkHighContrast,
    inverseOnSurface = InverseOnSurfaceDarkHighContrast,
    inversePrimary = InversePrimaryDarkHighContrast,
    surfaceDim = SurfaceDimDarkHighContrast,
    surfaceBright = SurfaceBrightDarkHighContrast,
    surfaceContainerLowest = SurfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = SurfaceContainerLowDarkHighContrast,
    surfaceContainer = SurfaceContainerDarkHighContrast,
    surfaceContainerHigh = SurfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = SurfaceContainerHighestDarkHighContrast,
)
